/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Login;

import mainmenu.menuutama;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.paint.Color.color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class formLogin extends javax.swing.JFrame {

    /** Creates new form formLogin */
    int dragxmouse;
    int dragymouse;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    private Connection koneksi;
    private Koneksi db = new Koneksi();
    
    public formLogin() {
        initComponents();
        //Koneksi.sambung();//
        this.setBackground(new Color(0,0,0,0));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_exit = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        btn_sign = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        user = new javax.swing.JTextField();
        database = new javax.swing.JTextField();
        namatabel = new javax.swing.JTextField();
        host = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(620, 10, 50, 50);

        pass.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pass.setText("xxxxxxxx");
        pass.setBorder(null);
        pass.setOpaque(false);
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(470, 220, 170, 30);

        btn_sign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign.png"))); // NOI18N
        btn_sign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_signMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_signMouseExited(evt);
            }
        });
        getContentPane().add(btn_sign);
        btn_sign.setBounds(287, 360, 160, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(240, 62, 250, 10);

        user.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        user.setText("username");
        user.setBorder(null);
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(100, 220, 170, 23);

        database.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        database.setText("database_name");
        database.setBorder(null);
        database.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                databaseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                databaseFocusLost(evt);
            }
        });
        getContentPane().add(database);
        database.setBounds(100, 270, 170, 23);

        namatabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        namatabel.setText("table_name");
        namatabel.setBorder(null);
        namatabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namatabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namatabelFocusLost(evt);
            }
        });
        getContentPane().add(namatabel);
        namatabel.setBounds(470, 270, 170, 23);

        host.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        host.setText("host");
        host.setBorder(null);
        host.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hostFocusLost(evt);
            }
        });
        getContentPane().add(host);
        host.setBounds(100, 320, 170, 23);

        port.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        port.setText("port");
        port.setBorder(null);
        port.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                portFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                portFocusLost(evt);
            }
        });
        getContentPane().add(port);
        port.setBounds(470, 320, 170, 23);

        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        password.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                passwordMouseDragged(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordMousePressed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(0, -10, 690, 450);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 680, 440);

        setSize(new java.awt.Dimension(684, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/closeexit.png"));
        btn_exit.setIcon(img);
        btn_exit.setToolTipText("Press to exit");
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/close.png"));
        btn_exit.setIcon(img);
    }//GEN-LAST:event_btn_exitMouseExited

    private void passwordMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-dragxmouse,y-dragymouse);
    }//GEN-LAST:event_passwordMouseDragged

    private void passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_passwordMousePressed

    private void btn_signMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signMouseEntered
       ImageIcon img = new ImageIcon(getClass().getResource("/images/sign2.png"));
        btn_sign.setIcon(img);
        btn_sign.setToolTipText("Press to login");
    }//GEN-LAST:event_btn_signMouseEntered

    private void btn_signMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/sign.png"));
        btn_sign.setIcon(img);
    }//GEN-LAST:event_btn_signMouseExited

    private void btn_signMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signMouseClicked
    String JDBC_DRIVER_CLASS = "com.mysql.cj.jdbc.Driver";
    String username = "root";
    String password = "";
    String hst = ""+host.getText();
    String prt = ""+port.getText();
    String passdb = String.valueOf(pass.getPassword());
    String dbName = ""+database.getText();
    String url = "jdbc:mysql://"+hst+":"+prt+"/"+dbName+"?useTimezone=true&serverTimezone=UTC";
    Connection kon = null;
        try {
            kon=DriverManager.getConnection(url,username,password);
            ResultSet rs = kon.createStatement().executeQuery("SELECT * FROM userpass WHERE username = '" + user.getText() + "'");
            if (rs.next()) {
                String passwordDB = rs.getString("pass");
                if (passwordDB.equalsIgnoreCase(Enkripsi_MD5.MD5(passdb))) {
                    new menuutama().setVisible(true);
                    dispose();      
                } else {
                    JOptionPane.showMessageDialog(null, "Masukan Data dengan Benar!!!");
        
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Masukan Data dengan Benar!!!");
            
        }
        
    }//GEN-LAST:event_btn_signMouseClicked

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        if(user.getText().equals("username")){
            user.setText("");
        }
        user.setForeground(Color.black);
    }//GEN-LAST:event_userFocusGained

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        if(user.getText().equals("")){
            user.setText("username");
        }
        user.setForeground(new Color(ERROR,WIDTH,ABORT));
        user.setForeground(Color.black);
    }//GEN-LAST:event_userFocusLost

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
       if(pass.getText().equals("xxxxxxxx")){
            pass.setText("");
        }
        pass.setForeground(Color.black);
    }//GEN-LAST:event_passFocusGained

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
                if(pass.getText().equals("")){
            pass.setText("xxxxxxxx");
        }
        pass.setForeground(new Color(ERROR,WIDTH,ABORT));
        pass.setForeground(Color.black);
    }//GEN-LAST:event_passFocusLost

    private void databaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_databaseFocusGained
       if(database.getText().equals("database_name")){
            database.setText("");
        }
       
    }//GEN-LAST:event_databaseFocusGained

    private void databaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_databaseFocusLost
        if(database.getText().equals("")){
        database.setText("database_name");
        }
        database.setForeground(new Color(ERROR,WIDTH,ABORT));
       
    }//GEN-LAST:event_databaseFocusLost

    private void namatabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namatabelFocusGained
        if(namatabel.getText().equals("table_name")){
        namatabel.setText("");
        }
    }//GEN-LAST:event_namatabelFocusGained

    private void namatabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namatabelFocusLost
        if(namatabel.getText().equals("")){
        namatabel.setText("table_name");
        }
        namatabel.setForeground(new Color(ERROR,WIDTH,ABORT));
       
    }//GEN-LAST:event_namatabelFocusLost

    private void hostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostFocusGained
        if(host.getText().equals("host")){
        host.setText("");
        }
    }//GEN-LAST:event_hostFocusGained

    private void hostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostFocusLost
        if(host.getText().equals("")){
        host.setText("host");
        }
        host.setForeground(new Color(ERROR,WIDTH,ABORT));
       
    }//GEN-LAST:event_hostFocusLost

    private void portFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_portFocusGained
        if(port.getText().equals("port")){
        port.setText("");
        }
    }//GEN-LAST:event_portFocusGained

    private void portFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_portFocusLost
        if(port.getText().equals("")){
        port.setText("port");
        }
        port.setForeground(new Color(ERROR,WIDTH,ABORT));
    }//GEN-LAST:event_portFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_sign;
    private javax.swing.JTextField database;
    private javax.swing.JTextField host;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField namatabel;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel password;
    private javax.swing.JTextField port;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

}
