/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataPerum;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mainmenu.menuutama;

/**
 *
 * @author HP
 */
public class Data_Perum extends javax.swing.JFrame {
    int idBaris = 0;
    String role;
    DefaultTableModel model;
    
    public Data_Perum() {
        initComponents();
        ModelTabel();
        ubah.setVisible(true);
        showForm(false);
        jPanel3.setVisible(false);
        hapus.setVisible(false);
        tambah.setVisible(false);
        cari.setVisible(false);
        txt_cari.setVisible(false);
        btn_lihat.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_cari = new javax.swing.JTextField();
        tambah = new javax.swing.JLabel();
        hapus = new javax.swing.JLabel();
        cari = new javax.swing.JLabel();
        btn_home = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_pengembang = new javax.swing.JTextField();
        txt_tiperumah = new javax.swing.JTextField();
        txt_file = new javax.swing.JTextField();
        simpan = new javax.swing.JLabel();
        tutup = new javax.swing.JLabel();
        ubah = new javax.swing.JLabel();
        btnfile = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        image = new javax.swing.JLabel();
        btn_lihat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_ok = new javax.swing.JLabel();
        database_name = new javax.swing.JTextField();
        table_name = new javax.swing.JTextField();
        host = new javax.swing.JTextField();
        port = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        txt_cari.setText("masukan kata kunci");
        txt_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariFocusLost(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        tambah.setForeground(new java.awt.Color(0, 0, 102));
        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaddbutton.png"))); // NOI18N
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambahMouseExited(evt);
            }
        });

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletebutton.png"))); // NOI18N
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hapusMouseExited(evt);
            }
        });

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchbutton.png"))); // NOI18N
        cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cariMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cariMouseExited(evt);
            }
        });

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });

        txt.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("INSERT CORRECT DATA FOR ACCESS DATABASE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(tambah)
                .addGap(18, 18, 18)
                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane1.setDividerSize(9);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Perumahan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No. Telephon");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pengembang");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tipe Perumahan");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("File Brosur");

        txt_file.setRequestFocusEnabled(false);

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simpanMouseExited(evt);
            }
        });

        tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tutup.png"))); // NOI18N
        tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tutupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tutupMouseExited(evt);
            }
        });

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ubah.png"))); // NOI18N
        ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ubahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ubahMouseExited(evt);
            }
        });

        btnfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        btnfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnfileMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(txt_notelp, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(txt_pengembang, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(txt_tiperumah, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_file, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(133, 133, 133))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tutup)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_pengembang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_tiperumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnfile, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jScrollPane3.setBackground(new java.awt.Color(51, 0, 102));
        jScrollPane3.setBorder(null);

        image.setBackground(new java.awt.Color(0, 0, 102));
        image.setOpaque(true);
        jScrollPane3.setViewportView(image);

        btn_lihat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lihat.png"))); // NOI18N
        btn_lihat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lihat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lihatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lihatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lihatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_lihat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 275, Short.MAX_VALUE))))
        );

        jSplitPane1.setRightComponent(jPanel5);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));

        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oke.png"))); // NOI18N
        btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
        });

        database_name.setText("database_name");
        database_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                database_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                database_nameFocusLost(evt);
            }
        });

        table_name.setText("table_name");
        table_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                table_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                table_nameFocusLost(evt);
            }
        });

        host.setText("host");
        host.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hostFocusLost(evt);
            }
        });

        port.setText("port");
        port.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                portFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                portFocusLost(evt);
            }
        });
        port.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                portKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(database_name, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table_name, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(btn_ok))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(database_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(table_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseEntered
       ImageIcon img = new ImageIcon(getClass().getResource("/images/deletebutton2.png"));
        hapus.setIcon(img);
        hapus.setToolTipText("Press to delete data");
    }//GEN-LAST:event_hapusMouseEntered

    private void hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseExited
       ImageIcon img = new ImageIcon(getClass().getResource("/images/deletebutton.png"));
        hapus.setIcon(img);
    }//GEN-LAST:event_hapusMouseExited

    private void cariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseEntered
        
    }//GEN-LAST:event_cariMouseEntered

    private void cariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseExited
       ImageIcon img = new ImageIcon(getClass().getResource("/images/searchbutton.png"));
       cari.setIcon(img);
    }//GEN-LAST:event_cariMouseExited

    private void simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/save2.png"));
        simpan.setIcon(img);
        simpan.setToolTipText("Press to save data");
            
        
    }//GEN-LAST:event_simpanMouseEntered

    private void simpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/save.png"));
        simpan.setIcon(img);
            
        
    }//GEN-LAST:event_simpanMouseExited

    private void tutupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutupMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/tutup2.png"));
        tutup.setIcon(img);
        tutup.setToolTipText("Press to close form");
    }//GEN-LAST:event_tutupMouseEntered

    private void tutupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutupMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/tutup.png"));
        tutup.setIcon(img);    }//GEN-LAST:event_tutupMouseExited

    private void txt_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusGained
        if(txt_cari.getText().equals("masukan kata kunci")){
        txt_cari.setText("");
        }
        txt_cari.setForeground(Color.black);    }//GEN-LAST:event_txt_cariFocusGained

    private void txt_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusLost
        if(txt_cari.getText().equals("")){
        txt_cari.setText("masukan kata kunci");
        }
        txt_cari.setForeground(new Color(ERROR,WIDTH,ABORT));
    }//GEN-LAST:event_txt_cariFocusLost

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
         simpanData();
        
    }//GEN-LAST:event_simpanMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
            if(idBaris == 0) {
            JOptionPane.showMessageDialog(this, "Pilih Data yang akan dihapus");
        }else{
            hapusData(idBaris);
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        role = "Ubah";
        int row = tabel.getRowCount();
        if (row > 0 ) {
            int sel = tabel.getSelectedRow();
            if(sel != -1){
            pilihData(tabel.getValueAt(sel, 0).toString());

          
        
            
        }
        }
                                        

    }//GEN-LAST:event_tabelMouseClicked

    private void tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutupMouseClicked
       resetForm();
       showForm(false);
       tutup.setEnabled(false);
       idBaris = 0;
    }//GEN-LAST:event_tutupMouseClicked

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        String key = txt_cari.getText();
        showData(key);
    }//GEN-LAST:event_txt_cariKeyReleased

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/home2.png"));
        btn_home.setIcon(img);
        btn_home.setToolTipText("Press to go home");
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/home.png"));
        btn_home.setIcon(img);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        this.dispose();
        menuutama main = new menuutama();
        main.setVisible(true);
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
    String JDBC_DRIVER_CLASS = "com.mysql.cj.jdbc.Driver";
    String username = "root";
    String host = ""+this.host.getText();
    String port = ""+this.port.getText();
    String password = "";
    String dbName = ""+database_name.getText();
    String url = "jdbc:mysql://"+host+":"+port+"/"+dbName+"?useTimezone=true&serverTimezone=UTC";
    Connection kon = null;
    try {
    Class.forName(JDBC_DRIVER_CLASS).newInstance();
    kon = DriverManager.getConnection(url,username,password);
        if (true) {
           showData("");
           jPanel3.setVisible(true);
           jPanel2.setVisible(false);
           hapus.setVisible(true);
           tambah.setVisible(true);
           cari.setVisible(true);
           txt_cari.setVisible(true);
           txt.setVisible(false);
           btn_lihat.setVisible(true);
        }else{
            
            
        }
    



    }   catch (ClassNotFoundException | IllegalAccessException |

    InstantiationException | SQLException e) {
    JOptionPane.showMessageDialog(rootPane, "Masukan Data Dengan Benar");

    

}
    }//GEN-LAST:event_btn_okMouseClicked

    private void database_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_database_nameFocusGained
        if(database_name.getText().equals("database_name")){
        database_name.setText("");
        }
       database_name.setForeground(Color.black);
    }//GEN-LAST:event_database_nameFocusGained

    private void database_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_database_nameFocusLost
        if(database_name.getText().equals("")){
        database_name.setText("database_name");
        }
        database_name.setForeground(new Color(ERROR,WIDTH,ABORT));
        database_name.setForeground(Color.black);
    }//GEN-LAST:event_database_nameFocusLost

    private void table_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_table_nameFocusGained
        if(table_name.getText().equals("table_name")){
        table_name.setText("");
        }
       table_name.setForeground(Color.black);
    }//GEN-LAST:event_table_nameFocusGained

    private void table_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_table_nameFocusLost
        if(table_name.getText().equals("")){
        table_name.setText("table_name");
        }
        table_name.setForeground(new Color(ERROR,WIDTH,ABORT));
        table_name.setForeground(Color.black);

    }//GEN-LAST:event_table_nameFocusLost

    private void hostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostFocusGained
        if(host.getText().equals("host")){
        host.setText("");
        }
        host.setForeground(Color.black);
    }//GEN-LAST:event_hostFocusGained

    private void hostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostFocusLost
        if(host.getText().equals("")){
        host.setText("host");
        }
        host.setForeground(new Color(ERROR,WIDTH,ABORT));
        host.setForeground(Color.black);
    }//GEN-LAST:event_hostFocusLost

    private void portFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_portFocusGained
        if(port.getText().equals("port")){
        port.setText("");
        }
        port.setForeground(Color.black);
    }//GEN-LAST:event_portFocusGained

    private void portFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_portFocusLost
        if(port.getText().equals("")){
        port.setText("port");
        }
        port.setForeground(new Color(ERROR,WIDTH,ABORT));
        port.setForeground(Color.black);
    }//GEN-LAST:event_portFocusLost

    private void ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseClicked
    int id = 0;
    String nama = txtnama.getText();
    String alamat = txt_alamat.getText();
    String no_telp = txt_notelp.getText();
    String email = txt_email.getText();
    String pengembang = txt_pengembang.getText();
    String tipe = txt_tiperumah.getText();
    String file = txt_file.getText();
    String namatabel = table_name.getText();
    if(nama.isEmpty() || alamat.isEmpty() || no_telp.isEmpty() || email.isEmpty() ||
    pengembang.isEmpty() || tipe.isEmpty() || file.isEmpty()){
    JOptionPane.showMessageDialog(this, "Pilih Data terlebih dahulu!!!");
        
    }else{
        ubahData();
    }
    }//GEN-LAST:event_ubahMouseClicked

    private void tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/aaddbutton.png"));
        tambah.setIcon(img);
    }//GEN-LAST:event_tambahMouseExited

    private void tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/addbutton2.png"));
        tambah.setIcon(img);
        tambah.setToolTipText("Press to add data");
    }//GEN-LAST:event_tambahMouseEntered

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
        role = "Tambah";
        tambah.setText("Simpan");
        idBaris = 0;
            resetForm();
            showForm(true);
            hapus.setEnabled(true);

    }//GEN-LAST:event_tambahMouseClicked

    private void ubahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/ubah2.png"));
        ubah.setIcon(img);
        ubah.setToolTipText("Press to update data");
    }//GEN-LAST:event_ubahMouseEntered

    private void ubahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/ubah.png"));
        ubah.setIcon(img);
        ubah.setToolTipText("Press to update data");
    }//GEN-LAST:event_ubahMouseExited

    private void portKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_portKeyPressed

    }//GEN-LAST:event_portKeyPressed

    private void btnfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfileMouseClicked
                JFileChooser pilih = new JFileChooser();
        pilih.showOpenDialog(null);
        File f = pilih.getSelectedFile();
        String filename = f.getAbsolutePath();
        txt_file.setText(filename);
            try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
                for (int readNum; (readNum = fis.read(buf))!=-1;) {
                bos.write(buf, 0, readNum);
                }
                attach_image = bos.toByteArray();
        } catch (Exception e) {
        }
            

    }//GEN-LAST:event_btnfileMouseClicked

    private void btnfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfileMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/file2.png"));
        btnfile.setIcon(img);
        btnfile.setToolTipText("Press to upload data");
    }//GEN-LAST:event_btnfileMouseEntered

    private void btnfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfileMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/file.png"));
        btnfile.setIcon(img);
    }//GEN-LAST:event_btnfileMouseExited

    private void btn_lihatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lihatMouseClicked
        Connection con;
    Statement st;
    ResultSet rs;
        try {
            String sql = "select file_brosur from perumahan where id='"+idBaris+"'";
    con = dataPerum.Koneksi.Sambung();
    st = con.createStatement();
    rs = st.executeQuery(sql);
            if (rs.next()) {
                byte[]image = rs.getBytes("file_brosur");
                format = new ImageIcon(image);
                this.image.setIcon(format);
                this.image.setSize(200, 200);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_lihatMouseClicked

    private void btn_lihatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lihatMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/lihat2.png"));
        btn_lihat.setIcon(img);
        btn_lihat.setToolTipText("Press to view");
    }//GEN-LAST:event_btn_lihatMouseEntered

    private void btn_lihatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lihatMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/lihat.png"));
        btn_lihat.setIcon(img);
    }//GEN-LAST:event_btn_lihatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Perum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Perum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Perum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Perum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Perum().setVisible(true);
            }
        });
    }
    private void ModelTabel(){
    Object[] kolom = {"no","Nama Perumahan","Alamat","No. Telphone","Email","Pengembang","Tipe Perumahan","File Brosur"};
    model = new DefaultTableModel(kolom,0) {
    boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false,false,false
    };
    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
    return canEdit [columnIndex];
    }
    };
    tabel.setModel(model);
    tabel.setRowHeight(20);
    tabel.getColumnModel().getColumn(0).setMinWidth(0);
    tabel.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    private void showForm(boolean b){
    jSplitPane1.setDividerLocation(-1);
    jSplitPane1.getLeftComponent().setVisible(b);
    }
    private void showData(String key){
    model.getDataVector().removeAllElements();
    String where = "";
    if(!key.isEmpty()){
    where += "WHERE nama_perumahan LIKE '%"+key+"%' "
    + "OR alamat_perumahan LIKE '%"+key+"%' "
    + "OR no_telp LIKE '%"+key+"%' "
    + "OR email LIKE '%"+key+"%' "
    + "OR pengembang LIKE '%"+key+"%' "
    + "OR tipe_perumahan LIKE '%"+key+"%'"
    + "OR file_brosur LIKE '%"+key+"%'";
}
    String sql = "SELECT * FROM perumahan "+where;
    Connection con;
    Statement st;
    ResultSet rs;
    int baris = 0;
    try {
    con = dataPerum.Koneksi.Sambung();
    st = con.createStatement();
    rs = st.executeQuery(sql);
    while (rs.next()) {
    Object id = rs.getInt(1);
    Object nama = rs.getString(2);
    Object alamat = rs.getString(3);
    Object no = rs.getString(4);
    Object email = rs.getString(5);
    Object pengembang = rs.getString(6);
    Object tipe_perumahan = rs.getString(7);
    Object file_brosur = rs.getString(8);

    Object[] data = {id,nama,alamat,no,email,pengembang,tipe_perumahan,file_brosur};

    model.insertRow(baris, data);

    baris++;

}
    st.close();
    con.close();
    tabel.revalidate();
    tabel.repaint();
    } catch (SQLException e) {
    System.err.println("showData(): "+e.getMessage());
}
}
    private void resetForm(){
    tabel.clearSelection();
    txtnama.setText("");
    txt_alamat.setText("");
    txt_notelp.setText("");
    txt_email.setText("");
    txt_pengembang.setText("");
    txt_tiperumah.setText("");
    txt_file.setText("");
    txtnama.requestFocus();
    }
    private void resetView(){
    resetForm();
    showForm(false);
    showData("");
    hapus.setEnabled(true);
    idBaris = 0;
}
    private void simpanData(){
    ResultSet rs;
    Connection con;
    Statement st;
    int id = 0;
    String nama = txtnama.getText();
    String alamat = txt_alamat.getText();
    String no_telp = txt_notelp.getText();
    String email = txt_email.getText();
    String pengembang = txt_pengembang.getText();
    String tipe = txt_tiperumah.getText();
    String file = attach_image.toString();
    
    String namatabel = table_name.getText();
    if(nama.isEmpty() || alamat.isEmpty() || no_telp.isEmpty() || email.isEmpty() ||
    pengembang.isEmpty() || tipe.isEmpty() || tipe.isEmpty()){
    JOptionPane.showMessageDialog(this, "Mohon lengkapi data!");
    }else{
    
    try {
        String sql =
    "insert into perumahan (id,nama_perumahan,alamat_perumahan,no_telp,email,pengembang,tipe_perumahan,file_brosur) values (?,?,?,?,?,?,?,?)";
    con = dataPerum.Koneksi.Sambung();
    st = con.createStatement();
        PreparedStatement statement = con.prepareStatement(sql);
        statement.setInt(1, id);
        statement.setString(2, txtnama.getText());
        statement.setString(3, txt_alamat.getText());
        statement.setString(4, txt_notelp.getText());
        statement.setString(5, txt_email.getText());
        statement.setString(6, txt_pengembang.getText());
        statement.setString(7, txt_tiperumah.getText());
        statement.setBytes(8, attach_image);
        statement.execute();
        resetView();
    
    
    JOptionPane.showMessageDialog(this,"Data telah disimpan!");

    } catch (Exception e) {

}
}
}
    
    private void hapusData(int baris){
    Connection con;
    Statement st;
    try {
    con = dataPerum.Koneksi.Sambung();
    st = con.createStatement();
    st.executeUpdate("DELETE FROM perumahan WHERE id="+baris);
    st.close();
    con.close();
    resetView();
    JOptionPane.showMessageDialog(this, "Data telah dihapus");
    } catch (SQLException e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
  }
}
    private void pilihData(String n){
    hapus.setEnabled(true);
    String sql = "SELECT * FROM perumahan WHERE id='"+n+"'";
    Connection con;
    Statement st;
    ResultSet rs;
    try {
    con = dataPerum.Koneksi.Sambung();
    st = con.createStatement();
    rs = st.executeQuery(sql);
    while (rs.next()) {
    int id = rs.getInt(1);
    String nama = rs.getString(2);
    String alamat = rs.getString(3);
    String no = rs.getString(4);
    String email = rs.getString(5);
    String pengembang = rs.getString(6);
    String tipe = rs.getString(7);
    String file = rs.getString(8);

    idBaris = id;
    txtnama.setText(nama);
    txt_alamat.setText(alamat);
    txt_notelp.setText(no);
    txt_email.setText(email);
    txt_pengembang.setText(pengembang);
    txt_tiperumah.setText(tipe);
    txt_file.setText(file);

}
    st.close();
    con.close();
    showForm(true);
    } catch (SQLException e) {
    System.err.println("pilihData(): "+e.getMessage());
}
        }
    private void ubahData(){
    String nama = txtnama.getText();
    String alamat = txt_alamat.getText();
    String no = txt_notelp.getText();
    String email = txt_email.getText();
    String pengembang = txt_pengembang.getText();
    String tipe = txt_tiperumah.getText();
    String file = txt_file.getText();
    if(nama.isEmpty() || alamat.isEmpty() || no.isEmpty() || email.isEmpty() ||
    pengembang.isEmpty() || tipe.isEmpty() || tipe.isEmpty()){
    JOptionPane.showMessageDialog(this, "Mohon lengkapi data!");
    }else{
    Connection con;
    Statement st;
    try {
    con = dataPerum.Koneksi.Sambung();
    int row = tabel.getSelectedRow();
    String value = (tabel.getModel().getValueAt(row, 0).toString());
    String sql = "update perumahan set nama_perumahan=?,alamat_perumahan=?,no_telp=?,email=?,pengembang=?,tipe_perumahan=?,file_brosur=? where id='"+idBaris+"'";
    PreparedStatement statement = con.prepareStatement(sql); 
        statement.setString(1, txtnama.getText());
        statement.setString(2, txt_alamat.getText());
        statement.setString(3, txt_notelp.getText());
        statement.setString(4, txt_email.getText());
        statement.setString(5, txt_pengembang.getText());
        statement.setString(6, txt_tiperumah.getText());
        statement.setBytes(7, attach_image);
        statement.execute();
        resetView();
    
    JOptionPane.showMessageDialog(this,"Data telah diubah!");
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
}
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_lihat;
    private javax.swing.JLabel btn_ok;
    private javax.swing.JLabel btnfile;
    private javax.swing.JLabel cari;
    private javax.swing.JTextField database_name;
    private javax.swing.JLabel hapus;
    private javax.swing.JTextField host;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField port;
    private javax.swing.JLabel simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField table_name;
    private javax.swing.JLabel tambah;
    private javax.swing.JLabel tutup;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_file;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JTextField txt_pengembang;
    private javax.swing.JTextField txt_tiperumah;
    private javax.swing.JTextField txtnama;
    private javax.swing.JLabel ubah;
    // End of variables declaration//GEN-END:variables
private ImageIcon format = null;
String filename = null;
int s = 0;
byte[] attach_image = null;
}
