/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data_admin;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.ABORT;
import static java.awt.image.ImageObserver.ERROR;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mainmenu.menuutama;

/**
 *
 * @author HP
 */
public class kelolaAdmin extends javax.swing.JFrame {
    int idBaris = 0;
    String role;
    DefaultTableModel model;
    
    public kelolaAdmin() {
        initComponents();
        ModelTabel();
        jPanel3.setVisible(false);
        hapus.setVisible(false);
        tambah.setVisible(false);
        cari.setVisible(false);
        txt_cari.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tambah = new javax.swing.JLabel();
        hapus = new javax.swing.JLabel();
        cari = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_home = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        database = new javax.swing.JTextField();
        nama_tabel = new javax.swing.JTextField();
        txt_host = new javax.swing.JTextField();
        txt_port = new javax.swing.JTextField();
        btn_ok = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_pass = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JLabel();
        btn_tutup = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(667, 97));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aaddbutton.png"))); // NOI18N
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tambahFocusGained(evt);
            }
        });
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambahMouseExited(evt);
            }
        });

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletebutton.png"))); // NOI18N
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hapusMouseExited(evt);
            }
        });

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchbutton.png"))); // NOI18N
        cari.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_cari.setText("masukan kata kunci");
        txt_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariFocusLost(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSERT CORRECT DATA FOR ACCESS DATABASE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambah)
                .addGap(18, 18, 18)
                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cari)
                .addGap(18, 18, 18)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tambah)
                                .addGap(16, 16, 16))))
                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );

        jPanel8.setBackground(new java.awt.Color(102, 0, 102));

        database.setText("database_name");
        database.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                databaseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                databaseFocusLost(evt);
            }
        });

        nama_tabel.setText("table_name");
        nama_tabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nama_tabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nama_tabelFocusLost(evt);
            }
        });

        txt_host.setText("host");
        txt_host.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_hostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_hostFocusLost(evt);
            }
        });

        txt_port.setText("port");
        txt_port.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_portFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_portFocusLost(evt);
            }
        });
        txt_port.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_portKeyPressed(evt);
            }
        });

        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oke.png"))); // NOI18N
        btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_okMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_okMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ok)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(database, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nama_tabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_host, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(database, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nama_tabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_host, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerSize(9);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("USERNAME");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("PASSWORD");

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_simpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_simpanMouseExited(evt);
            }
        });

        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ubah.png"))); // NOI18N
        btn_ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ubahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ubahMouseExited(evt);
            }
        });

        btn_tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tutup.png"))); // NOI18N
        btn_tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tutupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tutupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tutupMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(32, 32, 32)
                                .addComponent(txt_username))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(28, 28, 28)
                                .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_tutup)
                        .addGap(20, 20, 20))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ubah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tutup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel5.setBackground(new java.awt.Color(51, 0, 102));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jSplitPane1.setRightComponent(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void databaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_databaseFocusGained
         if(database.getText().equals("database_name")){
        database.setText("");
        }
       database.setForeground(Color.black);
    }//GEN-LAST:event_databaseFocusGained

    private void databaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_databaseFocusLost
         if(database.getText().equals("")){
        database.setText("database_name");
        }
        database.setForeground(new Color(ERROR,WIDTH,ABORT));
        database.setForeground(Color.black);
    }//GEN-LAST:event_databaseFocusLost

    private void nama_tabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nama_tabelFocusGained
        if(nama_tabel.getText().equals("table_name")){
        nama_tabel.setText("");
        }
       nama_tabel.setForeground(Color.black);
    }//GEN-LAST:event_nama_tabelFocusGained

    private void nama_tabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nama_tabelFocusLost
        if(nama_tabel.getText().equals("")){
        nama_tabel.setText("table_name");
        }
        nama_tabel.setForeground(new Color(ERROR,WIDTH,ABORT));
        nama_tabel.setForeground(Color.black);
    }//GEN-LAST:event_nama_tabelFocusLost

    private void txt_hostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_hostFocusGained
        if(txt_host.getText().equals("host")){
        txt_host.setText("");
        }
        txt_host.setForeground(Color.black);
    }//GEN-LAST:event_txt_hostFocusGained

    private void txt_hostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_hostFocusLost
        if(txt_host.getText().equals("")){
        txt_host.setText("host");
        }
        txt_host.setForeground(new Color(ERROR,WIDTH,ABORT));
        txt_host.setForeground(Color.black);
    }//GEN-LAST:event_txt_hostFocusLost

    private void txt_portFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_portFocusGained
        if(txt_port.getText().equals("port")){
        txt_port.setText("");
        }
        txt_port.setForeground(Color.black);
    }//GEN-LAST:event_txt_portFocusGained

    private void txt_portFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_portFocusLost
        if(txt_port.getText().equals("")){
        txt_port.setText("port");
        }
        txt_port.setForeground(new Color(ERROR,WIDTH,ABORT));
        txt_port.setForeground(Color.black);
    }//GEN-LAST:event_txt_portFocusLost

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
    String JDBC_DRIVER_CLASS = "com.mysql.cj.jdbc.Driver";
    String username = "root";
    String host = ""+txt_host.getText();
    String port = ""+txt_port.getText();
    String password = "";
    String dbName = ""+database.getText();
    String url = "jdbc:mysql://"+host+":"+port+"/"+dbName+"?useTimezone=true&serverTimezone=UTC";
    Connection kon = null;
    try {
    Class.forName(JDBC_DRIVER_CLASS).newInstance();
    kon = DriverManager.getConnection(url,username,password);
        if (true) {
           showData("");
           jPanel3.setVisible(true);
           jPanel8.setVisible(false);
           hapus.setVisible(true);
           tambah.setVisible(true);
           cari.setVisible(true);
           txt_cari.setVisible(true);
           jLabel1.setVisible(false);
           
        }else{
            
            
        }
    



    }   catch (ClassNotFoundException | IllegalAccessException |

    InstantiationException | SQLException e) {
    JOptionPane.showMessageDialog(rootPane, "Masukan Data Dengan Benar");

    

}
    }//GEN-LAST:event_btn_okMouseClicked

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
     simpanData();
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseClicked
        int id = 0;
    String username = txt_username.getText();
    String pass = txt_pass.getText();
    if(username.isEmpty() || pass.isEmpty()){
    JOptionPane.showMessageDialog(this, "Pilih Data terlebih dahulu!!!");
        
    }else{
        ubahData();
    }
    
    }//GEN-LAST:event_btn_ubahMouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        role = "Ubah";
        int row = tabel.getRowCount();
        if (row > 0 ) {
            int sel = tabel.getSelectedRow();
            if(sel != -1){
            pilihData(tabel.getValueAt(sel, 0).toString());
            
        
            
        }
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        if(idBaris == 0) {
            JOptionPane.showMessageDialog(this, "Pilih Data yang akan dihapus");
        }else{
            hapusData(idBaris);
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
        role = "Tambah";
        tambah.setText("");
        idBaris = 0;
            resetForm();
            showForm(true);
            hapus.setEnabled(true);
    }//GEN-LAST:event_tambahMouseClicked

    private void btn_tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tutupMouseClicked
       resetForm();
       showForm(false);
       btn_tutup.setEnabled(false);
       idBaris = 0;
       
    }//GEN-LAST:event_btn_tutupMouseClicked

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
       dispose();
       menuutama main = new menuutama();
       main.setVisible(true);
    }//GEN-LAST:event_btn_homeMouseClicked

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        String key = txt_cari.getText();
        showData(key);
    }//GEN-LAST:event_txt_cariKeyReleased

    private void txt_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusGained
        if(txt_cari.getText().equals("masukan kata kunci")){
        txt_cari.setText("");
        }
        txt_cari.setForeground(Color.black);    
    }//GEN-LAST:event_txt_cariFocusGained

    private void txt_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusLost
        if(txt_cari.getText().equals("")){
        txt_cari.setText("masukan kata kunci");
        }
        txt_cari.setForeground(new Color(ERROR,WIDTH,ABORT));
    }//GEN-LAST:event_txt_cariFocusLost

    private void txt_portKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_portKeyPressed

    }//GEN-LAST:event_txt_portKeyPressed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/home2.png"));
        btn_home.setIcon(img);
        btn_home.setToolTipText("Press to go home");
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/home.png"));
        btn_home.setIcon(img);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/oke2.png"));
        btn_ok.setIcon(img);
        btn_ok.setToolTipText("Press to access database");
    }//GEN-LAST:event_btn_okMouseEntered

    private void btn_okMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/oke.png"));
        btn_ok.setIcon(img);
    }//GEN-LAST:event_btn_okMouseExited

    private void tambahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tambahFocusGained

    }//GEN-LAST:event_tambahFocusGained

    private void tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/addbutton2.png"));
        tambah.setIcon(img);
        tambah.setToolTipText("Press to add data");
    }//GEN-LAST:event_tambahMouseEntered

    private void tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/aaddbutton.png"));
        tambah.setIcon(img);
    }//GEN-LAST:event_tambahMouseExited

    private void hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/deletebutton2.png"));
        hapus.setIcon(img);
        hapus.setToolTipText("Press to delete data");
    }//GEN-LAST:event_hapusMouseEntered

    private void hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/deletebutton.png"));
        hapus.setIcon(img);
    }//GEN-LAST:event_hapusMouseExited

    private void btn_simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/save2.png"));
        btn_simpan.setIcon(img);
        btn_simpan.setToolTipText("Press to save data");
    }//GEN-LAST:event_btn_simpanMouseEntered

    private void btn_simpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/save.png"));
        btn_simpan.setIcon(img);
    }//GEN-LAST:event_btn_simpanMouseExited

    private void btn_ubahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/ubah2.png"));
        btn_ubah.setIcon(img);
        btn_ubah.setToolTipText("Press to update data");
    }//GEN-LAST:event_btn_ubahMouseEntered

    private void btn_ubahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/ubah.png"));
        btn_ubah.setIcon(img);
    }//GEN-LAST:event_btn_ubahMouseExited

    private void btn_tutupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tutupMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("/images/tutup2.png"));
        btn_tutup.setIcon(img);
        btn_tutup.setToolTipText("Press to close form");
    }//GEN-LAST:event_btn_tutupMouseEntered

    private void btn_tutupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tutupMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("/images/tutup.png"));
        btn_tutup.setIcon(img);
    }//GEN-LAST:event_btn_tutupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kelolaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kelolaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kelolaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kelolaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kelolaAdmin().setVisible(true);
            }
        });
    }
    private void ModelTabel(){
    Object[] kolom = {"id","Username","Password"};
    model = new DefaultTableModel(kolom,0) {
    boolean[] canEdit = new boolean [] {
        false,false, false
    };
    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
    return canEdit [columnIndex];
    }
    };
    tabel.setModel(model);
    tabel.setRowHeight(20);
    tabel.getColumnModel().getColumn(0).setMinWidth(0);
    tabel.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    private void showForm(boolean b){
    jSplitPane1.setDividerLocation(-1);
    jSplitPane1.getLeftComponent().setVisible(b);
    }
    private void showData(String key){
    model.getDataVector().removeAllElements();
    String where = "";
    if(!key.isEmpty()){
    where += "WHERE username LIKE '%"+key+"%' "
    + "OR pass LIKE '%"+key+"%' ";
}
    String sql = "SELECT * FROM userpass "+where;
    Connection con;
    Statement st;
    ResultSet rs;
    int baris = 0;
    try {
    con = data_admin.Koneksi.Sambung();
    st = con.createStatement();
    rs = st.executeQuery(sql);
    while (rs.next()) {
    Object id = rs.getInt(1);
    Object name = rs.getString(2);
    Object pass = rs.getString(3);

    Object[] data = {id,name,pass};

    model.insertRow(baris, data);

    baris++;

}
    st.close();
    con.close();
    tabel.revalidate();
    tabel.repaint();
    } catch (SQLException e) {
    System.err.println("showData(): "+e.getMessage());
}
}
    private void resetForm(){
    tabel.clearSelection();
    txt_username.setText("");
    txt_pass.setText("");
    }
    private void resetView(){
    resetForm();
    showForm(false);
    showData("");
    hapus.setEnabled(true);
    idBaris = 0;
}
    private void simpanData(){
    int id = 0;
    String name = txt_username.getText();
    String paswd = txt_pass.getText();
    String namatabel = nama_tabel.getText();
    if(name.isEmpty() || paswd.isEmpty() ){
    JOptionPane.showMessageDialog(this, "Mohon lengkapi data!");
    }else{
    String sql = "INSERT INTO userpass values ('"+id+"','"+name+"',MD5('"+paswd+"'))";
    Connection con;                         
    Statement st;
    try {
    con = Koneksi.Sambung();
    st = con.createStatement();
    st.executeUpdate(sql);
    st.close();
    con.close();
    resetView();

    JOptionPane.showMessageDialog(this,"Data telah disimpan!");

    } catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "anda belum terkoneksi");
}
}
}
    
    private void hapusData(int baris){
    Connection con;
    Statement st;
    try {
    con = Koneksi.Sambung();
    st = con.createStatement();
    st.executeUpdate("DELETE FROM userpass WHERE id="+baris);
    st.close();
    con.close();
    resetView();
    JOptionPane.showMessageDialog(this, "Data telah dihapus");
    } catch (SQLException e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
  }
}
    private void pilihData(String n){
    hapus.setEnabled(true);
    String sql = "SELECT * FROM userpass WHERE id='"+n+"'";
    Connection con;
    Statement st;
    ResultSet rs;
    try {
    con = Koneksi.Sambung();
    st = con.createStatement();
    rs = st.executeQuery(sql);
    while (rs.next()) {
    int id = rs.getInt(1);
    String name = rs.getString(2);
    String passwd = rs.getString(3);

    idBaris = id;
    txt_username.setText(name);
    txt_pass.setText(passwd);
}
    st.close();
    con.close();
    showForm(true);
    } catch (SQLException e) {
    System.err.println("pilihData(): "+e.getMessage());
}
        }
    private void ubahData(){
    String name = txt_username.getText();
    String passwd = txt_pass.getText();
    if(name.isEmpty() || passwd.isEmpty() ){
    JOptionPane.showMessageDialog(this, "Mohon lengkapi data!");
    }else{
    String sql = "update userpass set username='"+name+"',pass=md5('"+passwd+"') where id='"+idBaris+"'";
    Connection con;
    Statement st;
    try {
    con = Koneksi.Sambung();
    st = con.createStatement();
    st.executeUpdate(sql);

    st.close();
    con.close();
    resetView();

    JOptionPane.showMessageDialog(this,"Data telah diubah!");
    } catch (SQLException e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
}
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_ok;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel btn_tutup;
    private javax.swing.JLabel btn_ubah;
    private javax.swing.JLabel cari;
    private javax.swing.JTextField database;
    private javax.swing.JLabel hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField nama_tabel;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel tambah;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_host;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
